import Card from "components/Card";
import Footer from "components/Footer";
import Head from "next/head";

export default function Home() {
  const cards = [
    {
      href: "https://nextjs.org/docs",
      title: "Documentation",
      text: "Find in-depth information about Next.js features and API.",
    },
    {
      href: "https://nextjs.org/learn",
      title: "Learn",
      text: "Learn about Next.js in an interactive course with quizzes!",
    },
    {
      href: "https://github.com/vercel/next.js/tree/master/examples",
      title: "Examples",
      text: "Discover and deploy boilerplate example Next.js projects.",
    },
    {
      href: "https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app",
      title: "Deploy",
      text: "Instantly deploy your Next.js site to a public URL with Vercel.",
    },
  ];

  return (
    <div className="container min-h-screen px-2 flex flex-col">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-10 flex-1 flex flex-col justify-center items-center sm:py-20">
        <h1 className="mb-6 text-center">
          Welcome to{" "}
          <a
            className="text-blue-600 hover:underline focus:underline active:underline"
            href="https://nextjs.org"
          >
            Next.js!
          </a>
        </h1>

        <p className="mb-12 text-center text-2xl">
          Get started by editing{" "}
          <code className="bg-gray-100 rounded-md p-3 text-base">
            pages/index.js
          </code>
        </p>

        <div className="max-w-xs p-4 grid gap-4 sm:max-w-3xl sm:grid-cols-2 sm:gap-8">
          {cards.map((card) => (
            <Card
              key={card.title}
              href={card.href}
              title={card.title}
              text={card.text}
            />
          ))}
        </div>
      </main>

      <Footer />
    </div>
  );
}
